/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'title' : string,
  'value' : string,
  'icon' : string,
}
export interface Book {
  'id' : bigint,
  'title' : string,
  'edition' : string,
  'subject' : string,
  'coverImageId' : string,
  'description' : string,
}
export interface ContactInfo {
  'hours' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
}
export interface Course {
  'id' : bigint,
  'features' : Array<string>,
  'duration' : string,
  'mode' : string,
  'name' : string,
  'price' : string,
}
export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'courseOrBook' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface FAQ {
  'id' : bigint,
  'question' : string,
  'order' : bigint,
  'answer' : string,
}
export interface HeroContent {
  'title' : string,
  'ctaText' : string,
  'subtitle' : string,
}
export interface SiteImage {
  'id' : bigint,
  'url' : string,
  'name' : string,
  'section' : string,
  'uploadedAt' : Timestamp,
}
export interface Testimonial {
  'id' : bigint,
  'studentName' : string,
  'text' : string,
  'isVisible' : boolean,
  'rating' : bigint,
  'qualification' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'deleteAchievement' : ActorMethod<[bigint], undefined>,
  'deleteBook' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteFAQ' : ActorMethod<[bigint], undefined>,
  'deleteSiteImage' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getHeroContent' : ActorMethod<[], [] | [HeroContent]>,
  'getSiteImages' : ActorMethod<[], Array<SiteImage>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'setAchievement' : ActorMethod<[Achievement], bigint>,
  'setBook' : ActorMethod<[Book], bigint>,
  'setContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'setCourse' : ActorMethod<[Course], bigint>,
  'setFAQ' : ActorMethod<[FAQ], bigint>,
  'setHeroContent' : ActorMethod<[HeroContent], undefined>,
  'setSiteImage' : ActorMethod<[SiteImage], bigint>,
  'setTestimonial' : ActorMethod<[Testimonial], bigint>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];