/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'value' : IDL.Text,
  'icon' : IDL.Text,
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'edition' : IDL.Text,
  'subject' : IDL.Text,
  'coverImageId' : IDL.Text,
  'description' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'duration' : IDL.Text,
  'mode' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'courseOrBook' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const HeroContent = IDL.Record({
  'title' : IDL.Text,
  'ctaText' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const SiteImage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'text' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
  'deleteBook' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
  'deleteSiteImage' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
  'getSiteImages' : IDL.Func([], [IDL.Vec(SiteImage)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'setAchievement' : IDL.Func([Achievement], [IDL.Nat], []),
  'setBook' : IDL.Func([Book], [IDL.Nat], []),
  'setContactInfo' : IDL.Func([ContactInfo], [], []),
  'setCourse' : IDL.Func([Course], [IDL.Nat], []),
  'setFAQ' : IDL.Func([FAQ], [IDL.Nat], []),
  'setHeroContent' : IDL.Func([HeroContent], [], []),
  'setSiteImage' : IDL.Func([SiteImage], [IDL.Nat], []),
  'setTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'value' : IDL.Text,
    'icon' : IDL.Text,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'edition' : IDL.Text,
    'subject' : IDL.Text,
    'coverImageId' : IDL.Text,
    'description' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'duration' : IDL.Text,
    'mode' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'courseOrBook' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const HeroContent = IDL.Record({
    'title' : IDL.Text,
    'ctaText' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const SiteImage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'text' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
    'deleteBook' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
    'deleteSiteImage' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
    'getSiteImages' : IDL.Func([], [IDL.Vec(SiteImage)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'setAchievement' : IDL.Func([Achievement], [IDL.Nat], []),
    'setBook' : IDL.Func([Book], [IDL.Nat], []),
    'setContactInfo' : IDL.Func([ContactInfo], [], []),
    'setCourse' : IDL.Func([Course], [IDL.Nat], []),
    'setFAQ' : IDL.Func([FAQ], [IDL.Nat], []),
    'setHeroContent' : IDL.Func([HeroContent], [], []),
    'setSiteImage' : IDL.Func([SiteImage], [IDL.Nat], []),
    'setTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };